name = "courtlistener-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install worker-build && worker-build --release"

[env.production]
name = "courtlistener-worker"

[env.staging]
name = "courtlistener-worker-staging"
