name = "courtlistener-worker"
main = "build/index.js"
compatibility_date = "2025-12-10"
workers_dev = true

[build]
command = "cargo install worker-build@^0.7 && worker-build --dev"

# Staging environment
[env.staging]
name = "courtlistener-worker-staging"
workers_dev = true

# Production environment
[env.production]
name = "courtlistener-worker-prod"
workers_dev = false




